#!/bin/bash

name=$(basename "$0")
directory="/var/cache/readme/"
theme="demo"

function help {
    printf "%s OPTIONS:\n" "$name"
    printf "\t %s -h|--help \t\t Print help information\n" "$name"
    printf "\t %s \t\t\t Answer questions interactivaly to generate readme\n" "$name"
    printf "\t %s -l|--list\t\t Return a list of all possible readme templates\n" "$name"
    printf "\t %s -t|--theme\t\t Use the theme present in said list\n" "$name"
    printf "\t %s -a|--add\t\t Add a homemade readme template \n" "$name"
    printf "\t %s -c|--config\t\t Instead of generating a readme interactivaly use a config to generate the readme from. \n" "$name"
    printf "\n\n"
    printf "EXTRA INFO\n"
    printf "\t Sample config can be found here: https://www.github.com/F0xedb/README-generator\n"
}

function generate () {
    read -p "What is your project name? " repo
    read -p "What is your github name/organization? " org_name
    read -p "What is your name/id? " usr_name
    read -p "What is your email? " usr_email
    read -p "What is the title? " title
    read -p "Give us a short description? " desc
    read -p "What is your documentation url? " doc
    read -p "What is your license? " license
    read -p "What is your image url? " image_url
    read -p "What is your image width in px? " width
    read -p "What is your image height in px? " height
}

function execute {
    sed "s;repo;$repo;g" "$directory""$theme" > README.md
    sed -i "s;org_name;$org_name;g" README.md
    sed -i "s;usr_name;$usr_name;g" README.md
    sed -i "s;usr_email;$usr_email;g" README.md
    sed -i "s;title;$title;g" README.md
    sed -i "s;desc_var;$desc;g" README.md
    sed -i "s;doc_var;$doc;g" README.md
    sed -i "s;license_var;$license;g" README.md
    sed -i "s;image_url;$image_url;g" README.md
    sed -i "s;width_img;$width;g" README.md
    sed -i "s;height_img;$height;g" README.md
}

function add { 
    if [[ -f "$2" ]]; then
            cp "$2" "$directory"
    else
            printf "You can only add files to the list"
            exit 1
    fi
}

function handler() {
    case "$1" in
        "-h"|"--help")
            help
            exit 0
        ;;
        "-a"|"--add")
            add
            exit 0
        ;;
        "-l"|"--list")
            /usr/bin/ls "$directory"
            exit 0
        ;;
        "-t"|"--theme")
            if [[ -f "$directory""$2" ]]; then
                    theme="$2"
            else
                    printf "Theme's can only be files inside %s use $name -l for a list" "$directory"
                    exit 1
            fi
        ;;
        "-c"|"--config")
            if [[ -f "$2" ]]; then
                source "$2"
            else
                    printf "Invalid config"
                    exit 2
            fi    
        ;;
    esac
}

handler "$1" "$2"

if [[ -f README.md ]]; then
 mv README.md README_old.md
fi

if [[ "$1" != "-c" && "$1" != "--config" ]]; then
    generate
fi

execute
