#!/bin/bash

name=$(basename "$0")

function help {
    printf "%s OPTIONS:\n" "$name"
    printf "\t %s -h|--help \t\t Print help information\n" "$name"
    printf "\t %s \t\t\t Answer questions interactivaly to generate readme\n" "$name"
}



if [[ "$1" == "-h" || "$1" == "--help" ]]; then
        help
        exit 0
fi

read -p "What is your project name? " repo
read -p "What is your github name/organization? " org_name
read -p "What is the title? " title
read -p "Give us a short description? " desc
read -p "What is your documentation url? " doc
read -p "What is your license? " license
read -p "What is your image url? " image_url
read -p "What is your image width in px? " width
read -p "What is your image height in px? " height

directory="/var/cache/readme/"


if [[ -f README.md ]]; then
 mv README.md README_old.md
fi


sed "s;repo;$repo;g" "$directory"demo > README.md
sed -i "s;org_name;$org_name;g" README.md
sed -i "s;title;$title;g" README.md
sed -i "s;desc_var;$desc;g" README.md
sed -i "s;doc_var;$doc;g" README.md
sed -i "s;license_var;$license;g" README.md
sed -i "s;image_url;$image_url;g" README.md
sed -i "s;width_img;$width;g" README.md
sed -i "s;height_img;$height;g" README.md
